### creando usuario
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "username": "set",
  "password": "1222lml"
}

### obteniendo token
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "set",
  "password": "1222lml"
}

### login usuario id 50
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "set",
  "password": "1222lml"
}

### update user
PATCH http://localhost:3000/api/user/pOP8LByQ1ALunlXOpdLZt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBPUDhMQnlRMUFMdW5sWE9wZExadCIsInVzZXJuYW1lIjoic2V0IiwicGFzc3dvcmQiOiIkMmIkMDUkaEIxL0VTVHB4ekFvVUUudUkzZy5tT2JtWEFoTFdkN3o1QzVkNUEyRGsxQ3YvUldQR3dMLjYiLCJpYXQiOjE3MDIwODg4OTh9.mhZW0QUlUljCNjatfKd-9lrM3hWh6H8xAMCNFGV2Mn8

{
  "username": "set of sem"
}