### url root
GET http://localhost:3000/

### get all users
GET http://localhost:3000/api/user

### get one user
GET http://localhost:3000/api/user/asasas

### post user
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "username": "carlosPaz224",
  "password": "12345a"
}

### delete user
DELETE http://localhost:3000/api/user/NJ_o8d3nbJ3wl9GhCxfLH