### like to post adding

POST http://localhost:3000/api/post/AxWa63yWeLn-jiN0iG1Mg/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBPUDhMQnlRMUFMdW5sWE9wZExadCIsInVzZXJuYW1lIjoic2V0IG9mIHNlbSIsInBhc3N3b3JkIjoiJDJiJDA1JGhCMS9FU1RweHpBb1VFLnVJM2cubU9ibVhBaExXZDd6NUM1ZDVBMkRrMUN2L1JXUEd3TC42IiwiaWF0IjoxNzA5NjY5MDcxLCJleHAiOjE3MDk2NjkzNzF9.a0iO73PkGS91Tsvj29flOeb2xmW3T3N6PE8Gr94YZ2s

###
GET http://localhost:3000/api/post/AxWa63yWeLn-jiN0iG1Mg/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBPUDhMQnlRMUFMdW5sWE9wZExadCIsInVzZXJuYW1lIjoic2V0IG9mIHNlbSIsInBhc3N3b3JkIjoiJDJiJDA1JGhCMS9FU1RweHpBb1VFLnVJM2cubU9ibVhBaExXZDd6NUM1ZDVBMkRrMUN2L1JXUEd3TC42IiwiaWF0IjoxNzA5NjkwMzQ0LCJleHAiOjE3MDk2OTIzNDR9.YqNotdJlJm57FzunGY-P1QKxH4zZupHQfmKoM8YkIGg

### 
GET http://localhost:3000/api/post/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InBPUDhMQnlRMUFMdW5sWE9wZExadCIsInVzZXJuYW1lIjoic2V0IG9mIHNlbSIsInBhc3N3b3JkIjoiJDJiJDA1JGhCMS9FU1RweHpBb1VFLnVJM2cubU9ibVhBaExXZDd6NUM1ZDVBMkRrMUN2L1JXUEd3TC42IiwiaWF0IjoxNzA5NjkwMzQ0LCJleHAiOjE3MDk2OTIzNDR9.YqNotdJlJm57FzunGY-P1QKxH4zZupHQfmKoM8YkIGg